### 注册用户
POST http://localhost:8081/user/register
Content-Type: application/json

{
    "username1": "1232",
    "password1": "234324",
    "registerCode": "234324"
}

### 注册用户发送验证码
POST http://localhost:8081/email/register/code
Content-Type: application/json

{
    "email": "1750930322@qq.com"
}