app:
  env: dev
  logPath: D:\\log

smtp:
  host: "smtp.qq.com"
  port: 587
  username: "1750930322@qq.com"
  password: ""
  from: "1750930322@qq.com"


redis:
  isCluster: false
  password: "123456"
  redisdb: 0
  redisAddr:
    - "127.0.0.1:6379"
    # - "127.0.0.1:7278"    # 集群可以打开
    # - "127.0.0.1:3489"    # 集群可以打开

mysql:
  SetMaxIdleConns: 20
  SetMaxOpenConns: 100
  SetConnMaxLifetime: 3600
  SetConnMaxIdleTime: 1800